name: bonappetit
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  appwrite: ^4.0.2
  appwheel_flutter: ^0.0.1
  appwrite_auth_kit: ^0.1.0
  bloc: ^8.0.3
  dio: ^4.0.6
  get: ^4.6.1
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  cached_network_image: ^3.2.0
  shared_preferences: ^2.0.13
  new_version: ^0.3.0
  photo_view: ^0.13.0
  image_picker: ^0.8.5
  rxdart: ^0.27.3
  flutter_icons: ^1.1.0
  connectivity_plus: ^2.3.0
  google_fonts: ^2.3.2
  font_awesome: ^5.10.1
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
